# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o6HRv0F-m_GQDd7EE6pYHA7KVtH_ob_
"""

def kasallik_tashxisi(belgi):
  if belgi == "istima":
    return "parasetamol iching"
  elif belgi == "gripp":
    return "taylol xot iching"
  elif belgi == "bosh og'rig'i":
    return "trimol iching"
  elif belgi == "tomoq og'rig'i":
    return "tanzelgon h iching"
  elif belgi == "oyoq og'rig'i":
    return "kyupen maz surting"
  elif belgi == "suyak sinishi":
    return "shifokorga murojat qiling"
  else:
    return "shifokorga murojat qiling"
belgi=input("kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)