# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11o6HRv0F-m_GQDd7EE6pYHA7KVtH_ob_
"""

def yolni_toping(manzil):
  if manzil == "Qo'qon":
    return "to'g'riga yuring"
  elif manzil == "Bog'dod":
    return "600 metrdan keyin chapga yuring"
  elif manzil == "Rishton":
    return "o'nga yuring"
  elif manzil == "Marg'ilon":
    return "ortga yuring"
  elif manzil == "Farg'ona":
    return "ortga va 1000 metrdan so'ng chapga yuring"
  elif manzil == "Oltiariq":
    return "ortga va o'nga"
  else:
    return "lokatsiyadan yordam oling"
manzil=input("qayerga borasiz")
natija=yolni_toping(manzil)
print(natija)